version: '3'

services:
  wp-admin-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wp-admin-api
    ports:
      - "7000:3000"
    volumes:
      - ./mock:/app/mock
      - ./sqlite:/app/sqlite
    env_file:
      - .env
    environment:
      - USERS=${USERS}
      - SERVERS=${SERVERS}
      - RESTART_COMMAND=${RESTART_COMMAND}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s