version: '3'

services:
  wp-admin-api:
    image: meldiron/wp-admin-api:${WP_ADMIN_API_VERSION}
    ports:
      - 7000:3000
    deploy:
      mode: replicated
      replicas: 2
      update_config:
          parallelism: 1
          delay: 10s
    volumes:
      - /root/lukasbarber:/mnt/lukasbarber:rw
      - ./sqlite/fiber.sqlite3:/app/sqlite/fiber.sqlite3
    env_file:
      - .env
    environment:
      - USERS=${USERS}
      - SERVERS=${SERVERS}
      - RESTART_COMMAND=${RESTART_COMMAND}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
