version: '3'

services:
  wp-admin-api:
    image: meldiron/wp-admin-api:${WP_ADMIN_API_VERSION}
    ports:
      - "3000:3000"
    volumes:
      - /root/lukasbarber:/mnt/lukasbarber:rw
    env_file:
      - .env
    environment:
      - USERS=${USERS}
      - SERVERS=${SERVERS}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
